[otp]
env = "dev"
rootPath = ""

[log]
level = "info"
rootPath = ""

[mysql]
address = "127.0.0.1:3306"
userName = "root"
"password@cipher" = "12345678"
db = "otp"
# 连接可复用的最大时间,分钟
connMaxLifeTime = 30
# 空闲连接池中连接的最大数量
maxIdleConn = 50
# 打开数据库连接的最大数量
maxOpenConn = 100
# 连接超时时间,秒
connMaxWaitTime = "20s"
