[server]
env = "dev"
rootPath = ""

[log]
# debug info error
level = "info"
rootPath = ""
appFile = "application.log"
# 每个日志文件最大大小(MB)
maxSize = 10
# 旧日志保留的个数
maxBackups = 100
# 旧日志保留的最大天数
maxAge = 30
# 是否压缩旧日志文件
compress = true

[mysql]
address = "127.0.0.1:3306"
userName = "root"
"password@cipher" = "12345678"
db = "otp"
# 连接可复用的最大时间,分钟
connMaxLifeTime = 30
# 空闲连接池中连接的最大数量
maxIdleConn = 50
# 打开数据库连接的最大数量
maxOpenConn = 100
# 连接超时时间,秒
connMaxWaitTime = "20s"
