[client]
namespaceId = ""
dataId = "otpserverv1"
group = "DEFAULT_GROUP"
timeoutMs = 5000
logDir = "/nacos/log"
cacheDir = "/nacos/cache"
logLevel = "info"
isListenChange = true
## server1
[[server]]
ip = "127.0.0.1"
port = 8848
contextPath = "/nacos"

## server 2
#[[server]]
#ip = "127.0.0.1"
#port = 8848
#contextPath = "/nacos"
