[server]
env = "dev"
port = 8066
rootPath = "./otpwork"
# 限速QPS
reqLimit = 100
# access token有效期(小时)
accessTokenValidHour = 4
# time token有效期(分钟)
timeTokenValidMinute = 2
# 服务域名(正式环境应该替换为相应的域名)
domain = "localhost"
# admin登陆态有效期(小时)
adminLoginValidHour = 12

[log]
# debug info error
level = "info"
rootPath = "/log/"
appFile = "app.log"
httpFile = "request.log"
# 每个日志文件最大大小(MB)
maxSize = 10
# 旧日志保留的个数
maxBackups = 100
# 旧日志保留的最大天数
maxAge = 30
# 是否压缩旧日志文件
compress = true

[store]
mainStore = "mysql" # 当前可选: mysql,pgsql
backupStore = "" # 当前可选: "",mysql,pgsql
rootPath = "/store/"
# 是否启用本地存储（数据冗余一份到本地磁盘） true | false
isEnableLocal = true
# 周期备份数据到本地，注意只有启用本地存储才有效，单位：小时
cycleBakToLocalHour = 4
# 是否启用内存存储（数据冗余一份到内存，优先查询） true | false
isEnableMemory = true

[mysql]
address = "127.0.0.1:3306"
userName = "root"
"password@cipher" = "ac1b926895e6982a7060f1ca10248659"
dbName = "otp"
# 连接可复用的最大时间,分钟
connMaxLifeTime = 30
# 空闲连接池中连接的最大数量
maxIdleConn = 30
# 打开数据库连接的最大数量
maxOpenConn = 200
# 连接超时时间,秒
connMaxWaitTime = "20s"

[pgsql]
host = "127.0.0.1"
port = "5432"
userName = "postgres"
"password@cipher" = ""
dbName = "otp"
