[server]
env = "dev"
port = 8066
rootPath = ""
# 限速QPS
reqLimit = 100
# access token有效期(小时)
accessTokenValidHour = 4
# time token有效期(分钟)
timeTokenValidMinute = 2

[log]
# debug info error
level = "info"
rootPath = ""
appFile = "app.log"
httpFile = "request.log"
# 每个日志文件最大大小(MB)
maxSize = 10
# 旧日志保留的个数
maxBackups = 100
# 旧日志保留的最大天数
maxAge = 30
# 是否压缩旧日志文件
compress = true

[store]
mainStore = "mysql"
backupStore = "pgsql"
# 是否启用本地存储（数据冗余一份到本地磁盘） true | false
isEnableLocal = false
# 是否启用内存存储（数据冗余一份到内存，优先查询） true | false
isEnableMemory = true

[mysql]
address = "127.0.0.1:3306"
userName = "root"
"password@cipher" = "ac1b926895e6982a7060f1ca10248659"
dbName = "otp"
# 连接可复用的最大时间,分钟
connMaxLifeTime = 30
# 空闲连接池中连接的最大数量
maxIdleConn = 30
# 打开数据库连接的最大数量
maxOpenConn = 200
# 连接超时时间,秒
connMaxWaitTime = "20s"

[pgsql]
host = "127.0.0.1"
port = "5432"
userName = "postgres"
"password@cipher" = "ac1b926895e6982a7060f1ca10248659"
dbName = "otp"
